twig:
    default_path: '%kernel.project_dir%/templates'
    paths:
        # directories are relative to the project root dir (but you
        # can also use absolute directories)
        '%kernel.project_dir%/templates/panel': panel
        '%kernel.project_dir%/templates/panel/categories': categorias
        '%kernel.project_dir%/templates/panel/products': productos
when@test:
    twig:
        strict_variables: true
